//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Growthstories.UI.Persistence {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Growthstories.UI.Persistence.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS Actions; DROP TABLE IF EXISTS Plants;.
        /// </summary>
        internal static string DeleteStorage {
            get {
                return ResourceManager.GetString("DeleteStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Actions WHERE 
        ///(
        ///(@PlantId IS NOT NULL AND PlantId = @PlantId)
        ///OR
        ///(@UserId IS NOT NULL AND UserId = @UserId)
        ///)
        ///ORDER BY UserRevision;.
        /// </summary>
        internal static string GetActions {
            get {
                return ResourceManager.GetString("GetActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Plants WHERE 
        ///(
        ///(@PlantId IS NOT NULL AND PlantId = @PlantId)
        ///OR
        ///(@UserId IS NOT NULL AND UserId = @UserId)
        ///);
        ///.
        /// </summary>
        internal static string GetPlants {
            get {
                return ResourceManager.GetString("GetPlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Actions
        ///(
        ///       UserId guid NOT NULL,
        ///       UserRevision int NOT NULL CHECK (UserRevision &gt; 0),
        ///       PlantId guid NOT NULL,
        ///       Payload blob NOT NULL,
        ///       CONSTRAINT PK_Actions PRIMARY KEY (UserId, UserRevision)
        ///);
        ///
        ///CREATE TABLE IF NOT EXISTS Plants
        ///(
        ///       UserId guid NOT NULL,
        ///       PlantId guid NOT NULL,
        ///       Payload blob NOT NULL,
        ///       CONSTRAINT PK_Plants PRIMARY KEY (UserId, PlantId)
        ///);.
        /// </summary>
        internal static string InitializeStorage {
            get {
                return ResourceManager.GetString("InitializeStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @Payload.
        /// </summary>
        internal static string Payload {
            get {
                return ResourceManager.GetString("Payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Actions 
        ///(UserId, UserRevision, PlantId, Payload) 
        ///VALUES(
        ///@UserId,@UserRevision,@PlantId,@Payload
        ///);.
        /// </summary>
        internal static string PersistAction {
            get {
                return ResourceManager.GetString("PersistAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Plants
        ///(UserId, PlantId, Payload) 
        ///VALUES(
        ///@UserId,@PlantId,@Payload
        ///);.
        /// </summary>
        internal static string PersistPlant {
            get {
                return ResourceManager.GetString("PersistPlant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @PlantId.
        /// </summary>
        internal static string PlantId {
            get {
                return ResourceManager.GetString("PlantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Actions; DELETE FROM Plants;.
        /// </summary>
        internal static string PurgeStorage {
            get {
                return ResourceManager.GetString("PurgeStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserId.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @UserRevision.
        /// </summary>
        internal static string UserRevision {
            get {
                return ResourceManager.GetString("UserRevision", resourceCulture);
            }
        }
    }
}
