//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Growthstories.Sync
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SyncSqlStatements
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SyncSqlStatements()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Growthstories.Sync.SyncSqlStatements", typeof(SyncSqlStatements).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SELECT StreamId, StreamRevision, Stamp
        ///  FROM Synchronizations;.
        /// </summary>
        internal static string GetSyncHeads
        {
            get
            {
                return ResourceManager.GetString("GetSyncHeads", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS Synchronizations
        ///(
        ///       StreamId guid NOT NULL,
        ///       StreamRevision int NULL,
        ///       Stamp datetime NULL,
        ///       CONSTRAINT PK_Commits PRIMARY KEY (StreamId)
        ///);
        ///CREATE INDEX IF NOT EXISTS IX_Stamp ON Commits (CommitStamp);.
        /// </summary>
        internal static string Initialize
        {
            get
            {
                return ResourceManager.GetString("Initialize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Synchronizations WHERE StreamId=@StreamId;.
        /// </summary>
        internal static string MarkPrivate
        {
            get
            {
                return ResourceManager.GetString("MarkPrivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Synchronizations (StreamId) VALUES(@StreamId);.
        /// </summary>
        internal static string MarkPublic
        {
            get
            {
                return ResourceManager.GetString("MarkPublic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to INSERT
        ///  INTO Synchronizations
        ///     ( StreamId, StreamRevision, Stamp)
        ///VALUES (@StreamId, @StreamRevision, @Stamp);.
        /// </summary>
        internal static string PersistSyncHead
        {
            get
            {
                return ResourceManager.GetString("PersistSyncHead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Synchronizations;.
        /// </summary>
        internal static string PurgeStorage
        {
            get
            {
                return ResourceManager.GetString("PurgeStorage", resourceCulture);
            }
        }
    }
}
