//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Growthstories.DomainTests.Sync {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Schema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Schema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Growthstories.DomainTests.Sync.Schema", typeof(Schema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;:&quot;object&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-03/schema&quot;,
        ///	&quot;extends&quot;: {&quot;$ref&quot;: &quot;ievent&quot;},
        ///	&quot;id&quot;: &quot;createentity&quot;,
        ///	&quot;required&quot;:true,
        ///	&quot;properties&quot;:{
        ///		&quot;parentAncestorId&quot;: {
        ///			&quot;type&quot;:&quot;string&quot;,
        ///			&quot;id&quot;: &quot;http://jsonschema.net/parentAncestorId&quot;,
        ///			&quot;required&quot;:true
        ///		},
        ///		&quot;parentId&quot;: {
        ///			&quot;type&quot;:&quot;string&quot;,
        ///			&quot;id&quot;: &quot;http://jsonschema.net/parentId&quot;,
        ///			&quot;required&quot;:true
        ///		}
        ///	}
        ///}.
        /// </summary>
        internal static string createevent {
            get {
                return ResourceManager.GetString("createevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;type&quot;:&quot;object&quot;,
        ///	&quot;$schema&quot;: &quot;http://json-schema.org/draft-03/schema&quot;,
        ///	&quot;id&quot;: &quot;ievent&quot;,
        ///	&quot;required&quot;:true,
        ///	&quot;properties&quot;:{
        ///		&quot;createdOn&quot;: {
        ///			&quot;type&quot;:&quot;number&quot;,
        ///			&quot;id&quot;: &quot;http://jsonschema.net/createdOn&quot;,
        ///			&quot;required&quot;:true
        ///		},
        ///		&quot;eventId&quot;: {
        ///			&quot;type&quot;:&quot;string&quot;,
        ///			&quot;id&quot;: &quot;http://jsonschema.net/eventId&quot;,
        ///			&quot;required&quot;:true
        ///		},
        ///		&quot;incId&quot;: {
        ///			&quot;type&quot;:&quot;number&quot;,
        ///			&quot;id&quot;: &quot;http://jsonschema.net/incId&quot;,
        ///			&quot;required&quot;:true
        ///		},
        ///		&quot;streamAncestor&quot;: {
        ///			&quot;type&quot;:&quot;string&quot;,
        ///			&quot;id&quot;: &quot;http://js [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ievent {
            get {
                return ResourceManager.GetString("ievent", resourceCulture);
            }
        }
    }
}
